### PR TITLE
Touched up on Question 3 and 4 for submission

### PR DESCRIPTION
**Pull request by lnsidiou5**

### CODE REVIEW

**Comment by lnsidiou5** [comment]
Feel free to review these changes, or we can go over them on Wednesday, there isn't much.

**Review by mkubovsky — COMMENTED** [review]
I can't really tell what changed in this format. Is there a way different way to view the changes?

**Comment by lnsidiou5** [comment]
> I can't really tell what changed in this format. Is there a way different way to view the changes?

You can view it in my fork here: https://github.com/lnsidiou5/CP02/tree/main

**Comment by mkubovsky** [comment]
> > I can't really tell what changed in this format. Is there a way different way to view the changes?
> 
> You can view it in my fork here: https://github.com/lnsidiou5/CP02/tree/main

Are we going to use Q4 (1).ipynb for the submission?

**Comment by lnsidiou5** [comment]
> > > I can't really tell what changed in this format. Is there a way different way to view the changes?
> > 
> > 
> > You can view it in my fork here: https://github.com/lnsidiou5/CP02/tree/main
> 
> Are we going to use Q4 (1).ipynb for the submission?

Yes, that is yours and is the one we will submit

**Pull request closed without merging**
